matrix:
  include:
    - language: python
      python: 2.7
      install:
        - pip install -U platformio
      before_script:
        - pwd
        - cd esp
      script:
        - echo 'Trying to build ESP'
        - pio run

    - language: python
      python: 2.7
      install:
        - pip install -U platformio
      before_script:
        - pwd
        - cd sam
      script:
        - echo 'Trying to build SAM'
        - ./first.sh

    - language: node_js
      node_js:
        - 7
      before_install:
        - cd mock-api
      install:
        - npm install
      before_script:
        - npm run api &
        - npm run web &
        - sleep 2
      script:
        - echo 'Running end to end tests with casperjs'
        - npm -v
        - node -v
        - pwd
        - ls
        - npm run test
